Add package manager detection in GitHub workflow

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -34,20 +34,24 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
+          echo "Checking for yarn.lock..."
           if [ -f "${{ github.workspace }}/web/yarn.lock" ]; then
+            echo "Found yarn.lock"
             echo "manager=yarn" >> $GITHUB_ENV
             echo "command=install" >> $GITHUB_ENV
             echo "runner=yarn" >> $GITHUB_ENV
             exit 0
-          elif [ -f "${{ github.workspace }}/web/package-lock.json" ]; then
+          fi
+          echo "Checking for package-lock.json..."
+          if [ -f "${{ github.workspace }}/web/package-lock.json" ]; then
+            echo "Found package-lock.json"
             echo "manager=npm" >> $GITHUB_ENV
             echo "command=ci" >> $GITHUB_ENV
             echo "runner=npx --no-install" >> $GITHUB_ENV
             exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
           fi
+          echo "Unable to determine package manager"
+          exit 1
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
